FROM fedora:latest

RUN dnf -y update \
    && dnf -y install \
        cmake \
        gcc \
        gcc-c++ \
        gdb \
        git \
        lapack-devel \
        lcov \
        make \
        valgrind \
    && dnf clean all

# build the tuv-x library with memcheck
COPY . /tuv-x/
RUN mkdir /build \
      && cd /build \
      && cmake \
            -DTUVX_ENABLE_MEMCHECK:BOOL=TRUE \
            -DCMAKE_BUILD_TYPE=DEBUG \
        /tuv-x \
      && make -j 8

WORKDIR /build
