FROM fedora:latest

RUN dnf -y update \
    && dnf -y install \
        cmake \
        gcc \
        gcc-c++ \
        gdb \
        git \
        lapack-devel \
        lcov \
        make \
        valgrind \
    && dnf clean all

# build the tuv-x library with coverage
COPY . /tuv-x/
RUN mkdir /build \
      && cd /build \
      && cmake -D TUVX_ENABLE_COVERAGE:BOOL=TRUE \
               -D CMAKE_BUILD_TYPE=COVERAGE \
               /tuv-x \
      && make -j 8

WORKDIR /build
