FROM fedora:latest

RUN dnf -y update \
    && dnf -y install \
        cmake \
        doxygen \
        gcc \
        gcc-c++ \
        git \
        make \
        python3 \
        python3-pip \
    && dnf clean all

# Copy the tuvx code
COPY . /tuv-x/

RUN pip3 install -r /tuv-x/docs/requirements.txt

ARG SUFFIX=""
ENV SWITCHER_SUFFIX=$SUFFIX

RUN mkdir /build \
      && cd /build \
      && cmake \
        -D TUVX_BUILD_DOCS=ON \
        /tuv-x \
      && make docs

WORKDIR /build
