name: Docker

on: [push, pull_request]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref || github.run_id }}
  cancel-in-progress: true

jobs:
  docker-build-and-test:
    if: github.event_name != 'pull_request' || github.event.pull_request.head.repo.full_name != github.event.pull_request.base.repo.full_name
    name: Build and Test - ${{ matrix.dockerfile }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        dockerfile:
          - Dockerfile
          - Dockerfile.coverage
          - Dockerfile.memcheck
          - Dockerfile.mpi
          - Dockerfile.mpi.memcheck
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Build Docker image
        run: docker build -t tuvx -f docker/${{ matrix.dockerfile }} .

      - name: Run tests in container
        if: matrix.dockerfile != 'Dockerfile.coverage'
        run: docker run --name test-container -t tuvx bash -c 'make test ARGS="--rerun-failed --output-on-failure"'

      - name: Run coverage tests in container
        if: matrix.dockerfile == 'Dockerfile.coverage'
        run: docker run --name test-container -t tuvx bash -c 'make coverage ARGS="--rerun-failed --output-on-failure"'

      - name: Copy coverage from container
        if: matrix.dockerfile == 'Dockerfile.coverage'
        run: docker cp test-container:build/coverage.info .

      - name: Upload coverage report
        if: matrix.dockerfile == 'Dockerfile.coverage'
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: coverage.info