name: Mac

on:
  push:
    branches:
      - main
      - cpp-rewrite
  pull_request:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref || github.run_id }}
  cancel-in-progress: true

jobs:
  apple-clang:
    runs-on: macos-latest
    strategy:
      fail-fast: false
      matrix:
        build_type: [Debug, Release]
    steps:
    - uses: actions/checkout@v4
    - name: Configure
      run: cmake -S . -B build -DCMAKE_BUILD_TYPE=${{ matrix.build_type }}
    - name: Build
      run: cmake --build build
    - name: Test
      run: ctest --test-dir build --output-on-failure

  gcc:
    runs-on: macos-latest
    strategy:
      fail-fast: false
      matrix:
        gcc_version: [14]
        build_type: [Debug, Release]
    env:
      CXX: g++-${{ matrix.gcc_version }}
      CC: gcc-${{ matrix.gcc_version }}
    steps:
    - uses: actions/checkout@v4
    - name: Configure
      run: cmake -S . -B build -DCMAKE_BUILD_TYPE=${{ matrix.build_type }}
    - name: Build
      run: cmake --build build
    - name: Test
      run: ctest --test-dir build --output-on-failure
