name: Ubuntu

on:
  push:
    branches:
      - main
      - cpp-rewrite
  pull_request:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  gcc:
    runs-on: ubuntu-24.04
    strategy:
      fail-fast: false
      matrix:
        gcc_version: [12, 13, 14]
        build_type: [Debug, Release]
    env:
      CXX: g++-${{ matrix.gcc_version }}
      CC: gcc-${{ matrix.gcc_version }}
    steps:
    - uses: actions/checkout@v4
    - name: Configure
      run: cmake -S . -B build -DCMAKE_BUILD_TYPE=${{ matrix.build_type }}
    - name: Build
      run: cmake --build build
    - name: Test
      run: ctest --test-dir build --output-on-failure

  clang:
    runs-on: ubuntu-24.04
    strategy:
      fail-fast: false
      matrix:
        clang_version: [17, 18]
        build_type: [Debug, Release]
    env:
      CXX: clang++-${{ matrix.clang_version }}
      CC: clang-${{ matrix.clang_version }}
    steps:
    - uses: actions/checkout@v4
    - name: Configure
      run: cmake -S . -B build -DCMAKE_BUILD_TYPE=${{ matrix.build_type }}
    - name: Build
      run: cmake --build build
    - name: Test
      run: ctest --test-dir build --output-on-failure
